export const SEARCH_INPUT = "SEARCH_INPUT";
export const RADIO_INPUT = "RADIO_INPUT";
export const REQUEST_ROBOTS_PENDING = "REQUEST_API_PENDING";
export const REQUEST_ROBOTS_SUCCESS = "REQUEST_API_SUCCESS";
export const REQUEST_ROBOTS_FAILED = "REQUEST_API_FAILED";
